---
title: "Transparency Flowcharts"
author: "Michael Jensen"
output: 
  html_document:
    fig_width: 8.5
    fig_height: 11
editor_options: 
  chunk_output_type: console
---
```{r, echo = FALSE}
library(DiagrammeR)
```

# Overview

```{r, echo = FALSE}
grViz(" digraph {

graph [label = Overview
       labelloc = top
       rankdir = TB
       fontsize = 16]

node [shape = box
      color = Chocolate
      fontsize = 12]
  Transparency

node [color = DodgerBlue]
  Salesforce
  'Inactive Entity \nReport'
  'Reports w/Parent \nReport'

node [color = ForestGreen]
  'Analytical Software'
  'Salesforce \nData Quality \nReports'
  'Compliance \nReport'
  'Quality \nReport'

node [color = Black]
  'Update & Enforcement \nProcess'
  
edge []
  Transparency
    -> {Salesforce; 'Analytical Software'}

edge [tailport = s
      headport = n]
  'Analytical Software'
    -> {'Salesforce \nData Quality \nReports'; 'Quality \nReport'; 
        'Compliance \nReport'}

edge [tailport = s
      headport = n]
  {'Compliance \nReport'; 'Quality \nReport'; 
  'Salesforce \nData Quality \nReports'; 'Inactive Entity \nReport'; 
  'Reports w/Parent \nReport'}
    -> 'Update & Enforcement \nProcess'

edge [tailport = s
      headport = n]
  Transparency
    -> 'Analytical Software'
  Salesforce
    -> {'Analytical Software'; 'Inactive Entity \nReport'; 
        'Reports w/Parent \nReport'}


{rank = same; Transparency; Salesforce}
{rank = same; 'Compliance \nReport'; 'Quality \nReport'; 
              'Salesforce \nData Quality \nReports'}
{rank = same; 'Inactive Entity \nReport'; 
              'Reports w/Parent \nReport'}
}")
```

# Update and Enforcement Process

```{r, echo = FALSE}
grViz(" digraph {


graph [label = 'Update & Enforcement Process'
       labelloc = top
       rankdir = TB
       fontsize = 16]

node [shape = box
      fontsize = 12]
  'OSA \nReview'
  'Division of Finance \nReview'
  'Update Request \nProcess'
  'Enforcement \nProcess'

node [color = DodgerBlue]
  10 [label = Salesforce]
  11 [label = Salesforce]

node [color = Chocolate]
  Transparency

{rank = same; 'Division of Finance \nReview'; 10}
{rank = same; 'Update Request \nProcess'; 'Enforcement \nProcess'}

edge []
  'Division of Finance \nReview'
    -> 10
  'Update Request \nProcess'
    -> 'Enforcement \nProcess'

edge [tailport = s]
  'Update Request \nProcess'
    -> 11

edge [tailport = s]
  'Enforcement \nProcess'
    -> Transparency

edge [tailport = s
      headport = nw]
  'Update Request \nProcess'
    -> Transparency

edge [tailport = s
      headport = ne]
  'Enforcement \nProcess'
    -> 11

edge [tailport = s
      headport = n]
  'OSA \nReview'
    -> {'Division of Finance \nReview'; 10}
  10
    -> {'Update Request \nProcess'; 'Enforcement \nProcess'}
}")
```

# Determine Compliance Status

```{r, echo = FALSE}
grViz(" digraph {

graph [label = 'Determine Transparency Compliance Status'
       labelloc = top
       rankdir = TB
       fontsize = 16]

node [shape = box
      fontsize = 12]
  'Update during next compliance check'

node [color = ForestGreen]
  'Entity submitted required reports?'
  1 [label = 'Yes']
  2 [label = 'No']
  'Day one of a compliance cycle, or entity missing a 60-day noticed report?'
  3 [label = 'Yes']
  4 [label = 'No']
  'Unexpired temporary exemption?'  
  7 [label = 'Yes']
  8 [label = 'No']
  'Within grace period?'
  9 [label = 'Yes']
  10 [label = 'No']
  'Upload in queue?'
  11 [label = 'Yes']
  12 [label = 'No']
  'Hold previously removed due to uploaded batch?'
  13 [label = 'Yes']
  14 [label = 'No']
  R
  
node [color = DodgerBlue]
  Salesforce  
  'T Status: Current' 
  'T Status: On Hold' 
  'T Status: Delinquent, Not Enforced'
  'T Status: Delinquent, Enforced'
  'OSA Status: Current' 
  'OSA Status: Delinquent' 
  'OSA Status: On Hold'

node [style = invis
      color = White]
  100

{rank = same; 1; 2}
{rank = same; 3; 4;}
{rank = same; 7; 8}
{rank = same; 9; 10}
{rank = same; 11; 12}
{rank = same; 13; 14}
{rank = same; 'Send 60-day notice';
              'Within grace period?'}
{rank = same; 'T Status: Current'; 
              'T Status: On Hold'; 
              'T Status: Delinquent, Not Enforced'; 
              'T Status: Delinquent, Enforced';
              Salesforce}
{rank = same; 'OSA Status: Current';
              'OSA Status: Delinquent';
              'OSA Status: On Hold'}
{rank = same; 'Entity submitted required reports?';
              R}
{rank = same; 'Update during next compliance check';
              100}

edge [tailport = s
      headport = n]
  'Entity submitted required reports?'
    -> {1 2}
  1
    -> 'T Status: Current'
  2
    -> 'Day one of a compliance cycle, or entity missing a 60-day noticed report?'
    -> {3 4}
  3
    -> 'Unexpired temporary exemption?'
    -> {7 8}
  4
    -> 'T Status: Delinquent, Not Enforced'
  7
    -> 'T Status: Delinquent, Not Enforced'
  8
    -> 'Within grace period?'
    -> {9 10}
  9
    -> 'T Status: Delinquent, Enforced'
  10
    -> 'Upload in queue?'
    -> {11 12}
  11
    -> 'T Status: Delinquent, Not Enforced'
  12
    -> 'Hold previously removed due to uploaded batch?'
    -> {13 14}
  13
    -> 'T Status: Delinquent, Not Enforced'
  14
    -> 'T Status: On Hold'

  {'T Status: Current';
   'T Status: Delinquent, Not Enforced'}
    -> 'OSA Status: Current'
  'T Status: Delinquent, Enforced'
    -> 'OSA Status: Delinquent' 
  'T Status: On Hold'
    -> 'OSA Status: On Hold'

  {'OSA Status: Current';
   'OSA Status: Delinquent';
   'OSA Status: On Hold'}
    -> 'Update during next compliance check'

  R
    -> Salesforce
    -> 100
}")
```