---
title: "Masked Employee Names - Washington Terrace"
output: html_notebook
---
***
# Program Description

The purpose of this program is to help Shari' Garrett, CFO for Washington Terrace City, identify and correct invalid employee names.

# Program

## Inputs, Packages & Data Connection

```{r}
t_id <- 615

library(odbc)
library(tidyverse)

odbc_aws <- dbConnect(odbc::odbc(), "transpAWS")
```

## Batch Table

```{sql, connection=odbc_aws, output.var="batch_table"}
SELECT 
  id,
  upload_date,
  processed_date,
  file_record_count,
  file_total_amount,
  begin_txn_date,
  end_txn_date,
  status,
  status_message
FROM batch
WHERE entity_id = ?t_id
ORDER BY upload_date DESC
```

## Transaction Tables

```{sql, connection=odbc_aws, output.var="transaction_table"}
SELECT *
FROM transaction
WHERE batch_id IN (
  SELECT id
  FROM batch
  WHERE entity_id = ?t_id)
```

```{r}
transaction <- 
  dbGetQuery(
    odbc_aws,
    paste("
          SELECT *
          FROM transaction
          WHERE batch_id IN (
            SELECT id
            FROM batch
            WHERE entity_id = ", t_id, ")"))
```

```{r}
table_years <- c(2009, 2010, 2011, 2012, 2013)

transaction_list <- list()

for (i in table_years) {
  transaction_list[[i]] <- 1 + 3
}


transaction <- 
  dbGetQuery(
    odbc_aws,
    paste("
          SELECT *
          FROM transaction", year, "
          WHERE batch_id IN (
            SELECT id
            FROM batch
            WHERE entity_id = ", t_id, ")"))
```

## Work

```{r}
masked_vendors <- 
  vendor_table %>% 
  filter(masked == 1 
         & id %in% vendor_summary_table$vendor_id) %>% 
  select(id, name, masked, title, createdDate)
```

```{r}
problem_years <- 
  vendor_summary_table %>% 
  filter(vendor_id %in% masked_vendors$id)
  
a <- 
  masked_vendors %>% 
  anti_join(problem_years, by = c("id" = "vendor_id"))
```

```{r}
masked_vendors %>% 
  write_csv(
    "C:/Users/mjensen1/Documents/1. Inbox/Masked Names.csv")
```
